#!/bin/bash
#
# make_montage :: make a montage of the output images
#			and store in tests/output/montage.jpg
#
# This script uses the ImageMagick "montage" utility
#
# Execute this script from the top-level directory in the
# repo

montage tests/output/bree*jpg -tile 3x3 -geometry +2+2 tests/output/montage.jpg
